import { Category, MenuItem } from './types';

export const COLORS = {
  black: '#0a0a0a',
  charcoal: '#1c1c1c',
  orange: '#ff6b00',
  cream: '#f5f5f0',
  red: '#dc2626',
};

export const MENU_ITEMS: MenuItem[] = [
  // Burgers
  {
    id: 'b1',
    name: 'Cruncher',
    description: 'Tenders, gouda, crudités, sauce classique',
    price: 350,
    category: Category.BURGERS,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'b2',
    name: 'Grillz',
    description: 'Bœuf, gouda, crudités, sauce classique',
    price: 'S 350 / M 550 / L 700',
    category: Category.BURGERS,
    popular: true,
    image: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'b3',
    name: 'Sirocco',
    description: 'Merguez, ratatouille, hash brown, sauce piquante',
    price: 650,
    category: Category.BURGERS,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'b4',
    name: 'Smash Lee',
    description: 'Viande chinoise, galette de riz, sauce teriyaki',
    price: 650,
    category: Category.BURGERS,
    image: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'b5',
    name: 'Cheesy AF',
    description: 'Bœuf, mozzarella, gouda & béchamel',
    price: 700,
    category: Category.BURGERS,
    popular: true,
    image: 'https://images.unsplash.com/photo-1586190848861-99c8a3fb7ea5?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'b6',
    name: 'Seaquel',
    description: 'Poisson pané, crevettes panées, surimi, sauce rouille',
    price: 700,
    category: Category.BURGERS,
    image: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'b7',
    name: 'Bad Guy',
    description: 'Bœuf, viande pastrami, sauce chorizo',
    price: 700,
    category: Category.BURGERS,
    image: 'https://images.unsplash.com/photo-1551782450-a2132b4ba21d?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'b8',
    name: 'Intik',
    description: 'Bœuf, filet de bœuf, mozzarella, crudités, sauce chimichurri',
    price: 800,
    category: Category.BURGERS,
    popular: true,
    image: 'https://images.unsplash.com/photo-1596662951482-0c4ba74a6df6?q=80&w=1000&auto=format&fit=crop',
  },
  // Loaded Fries
  {
    id: 'f1',
    name: 'Brux',
    description: 'Tenders, frites, gouda, sauce béchamel',
    price: 650,
    category: Category.LOADED_FRIES,
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'f2',
    name: 'Chunk',
    description: 'Bœuf, frites, gouda, sauce béchamel',
    price: 650,
    category: Category.LOADED_FRIES,
    image: 'https://images.unsplash.com/photo-1630384060421-cb20d0e0649d?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'f3',
    name: 'Mistral',
    description: 'Merguez, ratatouille, frites, gouda, sauce béchamel, sauce piquante',
    price: 650,
    category: Category.LOADED_FRIES,
    image: 'https://images.unsplash.com/photo-1573080496987-aeb7d53384c7?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'f4',
    name: 'Spice',
    description: 'Poulet tandoori, frites, gouda, sauce béchamel',
    price: 750,
    category: Category.LOADED_FRIES,
    image: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'f5',
    name: 'Rage',
    description: 'Bœuf fumé, bœuf, frites, gouda, sauce béchamel, sauce smokey',
    price: 750,
    category: Category.LOADED_FRIES,
    popular: true,
    image: 'https://images.unsplash.com/photo-1518013431117-eb1465fa5752?q=80&w=1000&auto=format&fit=crop',
  },
  // Sandwich
  {
    id: 's1',
    name: 'Le 129',
    description: 'Poulet tandoori et poulet maison, sauce classique (Frites incluses séparément)',
    price: 750,
    category: Category.SANDWICH,
    image: 'https://images.unsplash.com/photo-1553909489-cd47e3b4430f?q=80&w=1000&auto=format&fit=crop',
  },
  // Sides
  {
    id: 'sd1',
    name: 'Crunchbox',
    description: 'Box tenders 200g',
    price: 450,
    category: Category.SIDES,
  },
  {
    id: 'sd2',
    name: 'Fryzza',
    description: 'Mozzarella panée',
    price: 200,
    category: Category.SIDES,
  },
  {
    id: 'sd3',
    name: 'Ringz',
    description: 'Oignon rings',
    price: 150,
    category: Category.SIDES,
  },
  {
    id: 'sd4',
    name: 'Crispz',
    description: 'Barquette de frites',
    price: 150,
    category: Category.SIDES,
  },
  {
    id: 'sd5',
    name: 'Cheese',
    description: 'Gruyère / Camembert / Mozzarella',
    price: 100,
    category: Category.SIDES,
  },
  {
    id: 'sd6',
    name: 'Crack',
    description: 'Œuf frit',
    price: 50,
    category: Category.SIDES,
  },
  // Drinks
  {
    id: 'd1',
    name: 'Soda 24cl',
    price: 100,
    category: Category.DRINKS,
  },
  {
    id: 'd2',
    name: 'Soda 33cl',
    price: 150,
    category: Category.DRINKS,
  },
];
